resultado = input('Digite um valor qualquer: ')
# print('O tipo primitivo desse valor é ', type(resultado))
# print('O Resultado só tem espaços? ', resultado.isspace())
# print('O Resultado é numerico? ', resultado.isnumeric())
# print('O Resultado é alfanumerico? ', resultado.isalnum())
# print('O Resultado é alfabetico? ', resultado.isalpha())
# print('O Resultado é minusculo? ', resultado.islower())
# print('O Resultado é maisculo? ', resultado.isupper())
# print('O resultado é capitalizado? ', resultado.istitle())

print('O tipo primitivo desse valor é \033[1;31m{}\033[m'.format(type(resultado)))
print('O valor é alfanumerico? \033[1;32m{}\033[m'.format(resultado.isalnum()))
print('O valor é numerico? \033[1;32m{}\033[m'.format(resultado.isnumeric()))
print('O valor só tem espaços? \033[1;32m{}\033[m'.format(resultado.isspace()))
print('O valor é capitalizado? \033[1;32m{}\033[m'.format(resultado.istitle()))
print('O valor é minusculo? \033[1;32m{}\033[m'.format(resultado.islower()))
print('O valor é maiusculo? \033[1;32m{}\033[m'.format(resultado.isupper()))