resultado = input('Digite um valor qualquer: ')
# print('O tipo primitivo desse valor é ', type(resultado))
# print('O Resultado só tem espaços? ', resultado.isspace())
# print('O Resultado é numerico? ', resultado.isnumeric())
# print('O Resultado é alfanumerico? ', resultado.isalnum())
# print('O Resultado é alfabetico? ', resultado.isalpha())
# print('O Resultado é minusculo? ', resultado.islower())
# print('O Resultado é maisculo? ', resultado.isupper())
# print('O resultado é capitalizado? ', resultado.istitle())

print('O tipo primitivo desse valor é {}'.format(type(resultado)))
print('O valor é alfanumerico? {}'.format(resultado.isalnum()))
print('O valor é numerico? {}'.format(resultado.isnumeric()))
print('O valor só tem espaços? {}'.format(resultado.isspace()))
print('O valor é capitalizado? {}'.format(resultado.istitle()))
print('O valor é minusculo? {}'.format(resultado.islower()))
print('O valor é maiusculo? {}'.format(resultado.isupper()))